### ISSUE TITLE
Homework Finished

### ISSUE THREAD

**Issue by renestadler** [htl-perg-2019-20-5bhif/currency-converter-api-renestadler#1]
Dear Mr. Stropek!
I'd like to inform you that i've completed the currency converter exercise including both additional
points.

Furthermore I've found a slightly mistake in the readme.md as the following requests has to return a different amount.
`
https://localhost:5001/api/products/Bike/price?targetCurrency=GBP leads to { "price": 800.00 }
`

Yours,
René Stadler

**Comment by rstropek** [comment]
You are right, sorry. Thank you for pointing that out.

Greetings,
Rainer Stropek.
